### ISSUE TITLE
Update xchainpy_ethereum source 

### ISSUE THREAD

**Issue by ThorChadMerlin** [hoodieonwho/thorchain-arb#10]
I believe the new source of xchainpy_ethereum is:
https://github.com/xchainjs/xchainpy-lib
As opposed to the testnet version as stated in the README?

Using this new version it solves ```account.py``` line 5's import error:
```from xchainpy_ethereum.models.client_types import XChainClientParams```

For others:
* Git clone from repo above
* cd into xchainpy/
* run ```pip install xchainpy_ethereum/```

**Comment by hoodieonwho** [comment]
yep, the newest client has been pushed to official pypi, you can also just do "pip install xchainpy_ethereum" without having the source files.

**Comment by hoodieonwho** [comment]
i am currently building an oracle which returns arb profit at each 5 sec interval for all possible pairs, I will create a local mongodb since it would generate a lot of data.
