### ISSUE TITLE
thornode client doesn't seem to be the right one ?

### ISSUE THREAD

**Issue by bosanquet13** [hoodieonwho/thorchain-arb#11]
Hi there,

I was trying to get this to run last night, finally got all the various pips installed. But it seemed like the thornode client that i pulled in (using the instructions) is not what the code is expecting. The API being called on in the code is not to be found in source of the venv thornode client. 

This is what i have ...
```
(venv) ronoc@Conors-MacBook-Pro thorchain-arb % ls venv/lib/python3.8/site-packages/thor*
venv/lib/python3.8/site-packages/thornode_client:
__init__.py             api                     api_client.py           configuration.py        models                  rest.py

venv/lib/python3.8/site-packages/thornode_client-1.0.0.dist-info:
INSTALLER       METADATA        RECORD          REQUESTED       WHEEL           top_level.txt
(venv) ronoc@Conors-MacBook-Pro thorchain-arb %
```

In oracle.py (from line 57), 
none of these method calls seem supported by the above dependency ?

```
        self.thorNode_network = thornode_client.NetworkApi()
        self.thorNode_node = thornode_client.NodesApi()
        self.thorNode_pool = thornode_client.PoolsApi()
        self.thorNode_tx = thornode_client.TxApi()
        self.thorNode_vault = thornode_client.VaultsApi()
```

```
grep -r NodesApi venv/lib/python3.8/site-packages/thornode_client
```

**Comment by hoodieonwho** [comment]
https://github.com/hoodieonwho/thorchain-arb/blob/main/thornode_client/thornode_client/__init__.py
you can find those Api class in this ´´init.py´´ file, they are also in folder ``api/``

A brief update: thornode endpoint 1317 is being discarded from node operator, thorswap and thornode.thorchain.info now provide centralised interface to those api calls. You can alternatively run your own fullnode, which is the recommended approach.

**Comment by bosanquet13** [comment]
alright sorry, I hadn't installed the thornode client properly. Running a fullnode though requires helluva alot of rune though right ?

**Comment by hoodieonwho** [comment]
I will be closing this issue for now, since the thornode issue has been solved.
you can run a fullnode without bonding, which is simply observing the state of chain. However, it would require quite a good rig to run a fullnode, since you have to observe binance, litecoin, eth, and bitcoin chain.

**Comment by bosanquet13** [comment]
great stuff, thanks man
