### ISSUE TITLE
Cannot seem to install secp256k1==0.13.2

### ISSUE THREAD

**Issue by karthiknayak02** [hoodieonwho/thorchain-arb#7]
ERROR: Could not find a version that satisfies the requirement secp256k1==0.13.2 (from xchainpy-thorchain) (from versions: 0.1.1, 0.1.2, 0.1.5, 0.2.0, 0.3.0, 0.3.1, 0.5.1, 0.7.0, 0.7.2, 0.8.1, 0.8.2, 0.8.5, 0.9.0, 0.10.0, 0.11.0, 0.11.1, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2)

**Comment by hoodieonwho** [comment]
Do you have secp256k1 installed on your OS? the python package just allow the python script to use system's secp256k1 package. If you are using linux, you can check the dependencies required inside Docker File

**Comment by karthiknayak02** [comment]
Sorry I should I added more details:

I am on MacOS (Macbook pro). I do not have secp256k1 installed on my OS. 
I tried to build your Docker File to install secp256k1 but it does not seem to work. I get the following error: 
I am just using the command `docker build .`

------               
 => ERROR [4/7] RUN apt install -y python3.8 python3.8-venv python3.8-dev build-essential automake pkg-config libtool libffi-dev libgmp-dev lib  1.7s
------                                                                                                                                                
 > [4/7] RUN apt install -y python3.8 python3.8-venv python3.8-dev build-essential automake pkg-config libtool libffi-dev libgmp-dev libsecp256k1-dev libpython3.8-dev:                                                                                                                                     
#6 0.319                                                                                                                                              
#6 0.319 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
#6 0.319 
#6 0.328 Reading package lists...
#6 1.101 Building dependency tree...
#6 1.257 Reading state information...
**#6 1.689 E: Unable to locate package python3.8
#6 1.689 E: Couldn't find any package by glob 'python3.8'
#6 1.689 E: Couldn't find any package by regex 'python3.8'
#6 1.689 E: Unable to locate package python3.8-venv
#6 1.689 E: Couldn't find any package by glob 'python3.8-venv'
#6 1.689 E: Couldn't find any package by regex 'python3.8-venv'
#6 1.689 E: Unable to locate package python3.8-dev
#6 1.689 E: Couldn't find any package by glob 'python3.8-dev'
#6 1.689 E: Couldn't find any package by regex 'python3.8-dev'
#6 1.689 E: Unable to locate package libpython3.8-dev
#6 1.689 E: Couldn't find any package by glob 'libpython3.8-dev'
#6 1.689 E: Couldn't find any package by regex 'libpython3.8-dev'
------
executor failed running [/bin/sh -c apt install -y python3.8 python3.8-venv python3.8-dev build-essential automake pkg-config libtool libffi-dev libgmp-dev libsecp256k1-dev libpython3.8-dev]: exit code: 100**

**Comment by hoodieonwho** [comment]
Hey, docker isn't supposed to work for now, you need to google how to compile/install secp256k1 in your macos environment, without using python. After you have it installed in your macOs, you pip install to basically tell the python compiler you can use my secp256k1 package from the system. I think I installed it using brew on my mac

**Comment by ThorChadMerlin** [comment]
try:
`pip3 install secp256k1 --upgrade`
in your environment

**Comment by hoodieonwho** [comment]
closed, secp256k1 needs to be installed into OS first.
