### ISSUE TITLE
MONGO missing from main.py

### ISSUE THREAD

**Issue by ThorChadMerlin** [hoodieonwho/thorchain-arb#9]
Latest commit removed from line 20:
```
    cred = open("secret/mongodb", 'r')
    MONGO = DB(cred=cred.read())
    cred.close()
```
This breaks the code which follows when making calls to the db, since ```MONGO``` is not defined. Was this intentional?

**Comment by hoodieonwho** [comment]
fixed in latest commit, it was intentional for testing purpose.
